In [26]:
import pandas as pd
import numpy as np


In [27]:
np.random.seed(42)

n = 200

car_names = ["ritz", "sx4", "ciaz", "wagon r", "swift", "verna", "city", "i20", "baleno", "creta"]
fuel_types = ["Petrol", "Diesel","CNG","Electric"]
seller_types = ["Dealer", "Individual"]
transmissions = ["Manual", "Automatic"]

data = {
    "Car_Name": np.random.choice(car_names, n),
    "Year": np.random.randint(2005, 2022, n),
    "Present_Price": np.round(np.random.uniform(3, 20, n), 2),
    "Kms_Driven": np.random.randint(5000, 150000, n),
    "Fuel_Type": np.random.choice(fuel_types, n),
    "Seller_Type": np.random.choice(seller_types, n),
    "Transmission": np.random.choice(transmissions, n),
    "Owner": np.random.randint(0, 3, n)
}

df = pd.DataFrame(data)
# Selling price = Present price ka 50%–90%
df["Selling_Price"] = np.round(df["Present_Price"] * np.random.uniform(0.5, 0.9, n), 2)

# Save file
df.to_csv("car_price_dataset_200_rows.csv", index=False)

print(df.head())

  Car_Name  Year  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0     city  2015           6.33       80745    Petrol  Individual   
1  wagon r  2020           4.18       99456    Petrol  Individual   
2      i20  2020           4.71       58413    Diesel      Dealer   
3    swift  2005           3.31      102239    Petrol  Individual   
4     city  2013           4.61       47318    Diesel      Dealer   

  Transmission  Owner  Selling_Price  
0    Automatic      2           5.05  
1       Manual      0           2.36  
2       Manual      2           3.90  
3       Manual      1           2.76  
4    Automatic      2           3.24  


In [28]:
df

,Car_Name,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Selling_Price
0,city,2015,6.33,80745,Petrol,Individual,Automatic,2,5.05
1,wagon r,2020,4.18,99456,Petrol,Individual,Manual,0,2.36
2,i20,2020,4.71,58413,Diesel,Dealer,Manual,2,3.90
3,swift,2005,3.31,102239,Petrol,Individual,Manual,1,2.76
4,city,2013,4.61,47318,Diesel,Dealer,Automatic,2,3.24
...,...,...,...,...,...,...,...,...,...
195,i20,2005,3.25,91740,CNG,Individual,Manual,2,1.98
196,swift,2005,8.96,20524,Diesel,Individual,Automatic,1,6.60
197,wagon r,2012,13.03,136149,Electric,Individual,Automatic,1,11.27
198,sx4,2014,9.67,130501,Petrol,Dealer,Manual,2,5.65


In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       200 non-null    object 
 1   Year           200 non-null    int32  
 2   Present_Price  200 non-null    float64
 3   Kms_Driven     200 non-null    int32  
 4   Fuel_Type      200 non-null    object 
 5   Seller_Type    200 non-null    object 
 6   Transmission   200 non-null    object 
 7   Owner          200 non-null    int32  
 8   Selling_Price  200 non-null    float64
dtypes: float64(2), int32(3), object(4)
memory usage: 11.8+ KB


In [30]:
df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'Electric', 'CNG'], dtype=object)

In [31]:
df.isnull().sum()

Car_Name         0
Year             0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
Selling_Price    0
dtype: int64

In [32]:
df['Owner'].value_counts()

Owner
0    78
2    62
1    60
Name: count, dtype: int64

In [34]:
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()
df['Fuel_Type']=encoder.fit_transform(df['Fuel_Type'])

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       200 non-null    object 
 1   Year           200 non-null    int32  
 2   Present_Price  200 non-null    float64
 3   Kms_Driven     200 non-null    int32  
 4   Fuel_Type      200 non-null    int64  
 5   Seller_Type    200 non-null    object 
 6   Transmission   200 non-null    object 
 7   Owner          200 non-null    int32  
 8   Selling_Price  200 non-null    float64
dtypes: float64(2), int32(3), int64(1), object(3)
memory usage: 11.8+ KB


In [36]:
df.duplicated().count()

np.int64(200)

In [37]:
df2=df.select_dtypes(['int','float'])
df2

,Year,Present_Price,Kms_Driven,Fuel_Type,Owner,Selling_Price
0,2015,6.33,80745,3,2,5.05
1,2020,4.18,99456,3,0,2.36
2,2020,4.71,58413,1,2,3.90
3,2005,3.31,102239,3,1,2.76
4,2013,4.61,47318,1,2,3.24
...,...,...,...,...,...,...
195,2005,3.25,91740,0,2,1.98
196,2005,8.96,20524,1,1,6.60
197,2012,13.03,136149,2,1,11.27
198,2014,9.67,130501,3,2,5.65


In [38]:
df2.corr()

,Year,Present_Price,Kms_Driven,Fuel_Type,Owner,Selling_Price
Year,1.000000,0.132120,0.071628,0.075084,-0.006717,0.189547
Present_Price,0.132120,1.000000,0.010887,0.045658,0.059441,0.920310
Kms_Driven,0.071628,0.010887,1.000000,-0.030302,0.083691,0.007336
Fuel_Type,0.075084,0.045658,-0.030302,1.000000,-0.010179,0.042144
Owner,-0.006717,0.059441,0.083691,-0.010179,1.000000,0.034937
Selling_Price,0.189547,0.920310,0.007336,0.042144,0.034937,1.000000


In [39]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Year           200 non-null    int32  
 1   Present_Price  200 non-null    float64
 2   Kms_Driven     200 non-null    int32  
 3   Fuel_Type      200 non-null    int64  
 4   Owner          200 non-null    int32  
 5   Selling_Price  200 non-null    float64
dtypes: float64(2), int32(3), int64(1)
memory usage: 7.2 KB


In [40]:
x=df[['Year','Present_Price','Fuel_Type','Kms_Driven']]
y=df2['Selling_Price']

In [41]:
from sklearn import linear_model

In [42]:
regr=linear_model.LinearRegression()
regr.fit(x,y)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [43]:
df2["Fuel_Type"].unique()

array([3, 1, 2, 0])

In [44]:
predicted=regr.predict([[2022,12.5,1,20000]])
predicted

C:\Users\ABHISHEK YADAV\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.35217568])

In [45]:
predicted2=regr.predict(x)
predicted2

array([ 4.51802232,  3.24312004,  3.68458992,  1.82553388,  3.2494114 ,
       10.1550174 ,  3.31934764,  5.61001087, 12.01286367,  2.08714262,
       11.81038214,  5.46504508,  3.02926338, 10.4400811 ,  9.57781021,
       12.69477789, 10.55691215, 11.88735891,  5.45296734,  3.89478355,
       10.95881699, 12.11939082, 14.38430037,  7.54132532,  6.21119549,
       10.99585237,  6.50765701, 13.4418073 , 12.21905645,  7.03580015,
       11.16271685, 11.24656763,  2.97230252, 13.30147836,  8.58643681,
       11.73418535,  5.51795495, 13.00961124,  7.24744818,  2.13606403,
       12.75591523,  3.00073923,  5.88189986, 13.216272  , 13.87340515,
        8.65871398,  9.94947043,  7.17734723,  5.35551821,  6.35895292,
       10.20383767, 10.85652393, 11.13392827, 11.28154406,  2.67851321,
        8.27174357,  3.17574733,  8.64256166,  7.2928301 , 12.44065566,
        6.68962566,  3.04380598,  4.13324556, 11.40199727,  9.81176451,
        3.16282193,  2.94362027, 10.74883214,  2.88779084, 11.68

In [46]:
from sklearn.metrics import r2_score
print(r2_score(y,predicted2))

0.8517525895279572
