In [1]:
# statistics
# 1. Descriptive Statistics
# 2. Inferential Statistics
import pandas as pd





In [33]:
df=pd.read_excel(r"C:\Users\ABHISHEK YADAV\Downloads\Raw data .xlsx")
df
# df['Salary'].corr(df['Mobile no.'])

,Id,Name,Lastname,Salary,Department,Mobile no.
0,1,Anshu,Rajput,90000,Sales,8595787610
1,2,Manish,Kumar,62000,Marketing,8595787611
2,3,Aadil,Khan,70000,Finance,8595787612
3,4,Chandan,Thakur,80000,IT,8595787613
4,5,Aman,Anand,20000,Sales,8595787614
5,6,Badal,Singh,65000,Marketing,8595787615
6,7,Anil,Yadav,55000,Finance,8595787616
7,8,Akash,Verma,75000,IT,8595787617
8,9,Yash,Kushwaha,25000,Sales,8595787618
9,10,Abhishek,Yadav,95000,Marketing,8595787619


In [3]:
# discriptive satatics
# mean = sum of total Divide by len of total
# medain = arrange ascending and mid point divide by 2 
# mode = higest repeated value 
# varience = gap of two data value 
# std(standard deviasion) = square root of variance
# corr = 0-0.2 (week) ,0.2-0.5 (good) , 0.7-0.9 (excelent)  is negative same 
# covarience = jab hume pata karna ho ki do variables (X aur Y) ek saath kaise move karte hain.

# feature engerring =coulmn convert string ,feature clean , feature scaling, feature selcting .,feature transfoem , featur normalization 

In [4]:
import numpy as np
v=np.array([2,5,4,9,3,8])
v


array([2, 5, 4, 9, 3, 8])

In [10]:
a=np.var(v)

In [11]:
m=np.mean(v)
m


np.float64(5.166666666666667)

In [12]:
y=m-v
y

array([ 3.16666667,  0.16666667,  1.16666667, -3.83333333,  2.16666667,
       -2.83333333])

In [13]:
b=y**2
b

array([10.02777778,  0.02777778,  1.36111111, 14.69444444,  4.69444444,
        8.02777778])

In [17]:
np.std(v)
c=np.sqrt(v)
c

array([1.41421356, 2.23606798, 2.        , 3.        , 1.73205081,
       2.82842712])

In [34]:
x=np.array([5,10,5,11,12,4,3,2,7,1])
y=np.array([1,6,2,8,5,1,4,6,5,2])
print(x*x)   #square of x
print(y*y)   #square of y
print(x*y)   #y multiple x



[ 25 100  25 121 144  16   9   4  49   1]
[ 1 36  4 64 25  1 16 36 25  4]
[ 5 60 10 88 60  4 12 12 35  2]


this is the purpose of the control and parts of the purticular parphapas
